name: CI

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: uv sync
      - name: Run Ruff
        run: uv run ruff check .

  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.14"
      - name: Install dependencies
        run: uv sync
      - name: Run pyright
        run: uv run pyright

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]
        rust-version:
          - "1.30" # resolve.nodes.deps, required-features
          - "1.33" # links
          - "1.35" # no null in resolve.nodes.deps for non-lib deps
          - "1.37" # doctest
          - "1.39" # publish
          - "1.40" # --filter-platform
          - "1.41" # dep_kinds kind/platform
          - "1.42" # dep_kinds de-duplication
          - "1.47" # test, deterministic ordering
          - "1.49" # homepage, documentation
          - "1.50" # doc
          - "1.51" # path
          - "1.55" # default_run
          - "1.58" # rust_version
          - "1.71" # workspace_default_members
          - "1.79" # underscores in inferred lib names
        include:
          - python-version: "3.10"
            rust-version: "stable"
          - python-version: "3.11"
            rust-version: "stable"
          - python-version: "3.12"
            rust-version: "stable"
          - python-version: "3.13"
            rust-version: "stable"
          - python-version: "3.14"
            rust-version: "stable"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        run: uv run pytest
